name:                haskell-database
version:             0.1.0.0
github:              "githubuser/haskell-database"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-database#readme>

dependencies:
- base >= 4.7 && < 5
- zeromq4-haskell
- binary
- flat >= 0.3.2
- bytestring
- connection

library:
  source-dirs: src

executables:
  hwserver:
    main:                Main.hs
    source-dirs:         hwserver
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-database
  hwclient:
    main:                Main.hs
    source-dirs:         hwclient
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-database
  haskell-database-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-database
  haskell-database2-exe:
    main:                Main.hs
    source-dirs:         app2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-database
tests:
  haskell-database-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-database
